export const path = {
	LOGIN: '/login',
	HOME: '/',
	PROFILE: '/profile',
	SUPPORT_SUTDENT: '/support-student',
	INFO_STUDENT: '/info-student',
	REPORT_FORM: '/report-form',
	SEMESTERS: '/semesters',
	STATUS: '/status',
	NARROWS: '/narrows',
	MAJOR: '/major',
	REPORT: '/report',
	EMPLOYEE_MANAGER: '/employee-manager',
	CAMPUS_MANAGER: '/campus-manager',
	FORM_REGISTER: '/form-register',
	REVIEW_CV: '/review-cv',
	REVIEW_FORM: '/review-form',
	REVIEW_REPORT: '/review-report',
	UP_FILE: '/up-file',
	COMPANY: '/company',
	WAIT_COMPANY: '/wait-company',
	REQUEST_FORM_STUDENT: '/request-form-student',
	NOT_FOUND: '*',
};
